name: ci_cd
on: workflow_dispatch
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
        with:
          path: .
      - name: Setup Nodejs
        uses: actions/setu-node@v4
        with:
          node-version: 14
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm build
      - name: Configure Git
        run: |
          git config --global user.name "Github Action"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      - name: Deploy to Github Pages
        run: npm deploy
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
